# === AUTOGENERATED FROM C++ ===


class Student:
    def __init__(self, name, age, averageGrade):
        self.name = name
        self.age = age
        self.averageGrade = averageGrade

def printStudentInfo(s):
    print(f"Имя: {s.name}")
    print(f"Возраст: {s.age} лет")
    print(f"Средний балл: {s.averageGrade}")
    print("-------------------")

def checkPerformance(grade):
    if grade >= 4.5:
        return "Отличник"
    elif grade >= 3.5:
        return "Хорошист"
    elif grade >= 2.5:
        return "Троечник"
    else:
        return "Неуспевающий"

def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

def processArray():
    SIZE = 5
    numbers = []
    print(f"Введите {SIZE} чисел:")
    for i in range(SIZE):
        num = int(input(f"Число {i + 1}: "))
        numbers.append(num)

    total = sum(numbers)
    print(f"Сумма элементов: {total}")
    print(f"Максимальный элемент: {max(numbers)}")
    print(f"Минимальный элемент: {min(numbers)}")
    print(f"Среднее значение: {total / SIZE}")

def main():
    print("=== ПРОГРАММА ДЛЯ УПРАВЛЕНИЯ СТУДЕНТАМИ ===")

    num1 = int(input("Введите первое число: "))
    num2 = int(input("Введите второе число: "))

    print("Результаты операций:")
    print(f"{num1} + {num2} = {num1 + num2}")
    print(f"{num1} - {num2} = {num1 - num2}")
    print(f"{num1} * {num2} = {num1 * num2}")

    if num2 != 0:
        print(f"{num1} / {num2} = {num1 / num2}")
    else:
        print("Деление на ноль!")

    student1 = Student("Иван Петров", 20, 4.8)
    student2 = Student("Мария Сидорова", 19, 3.7)
    student3 = Student("Алексей Иванов", 21, 2.9)

    print("Информация о студентах:")
    printStudentInfo(student1)
    printStudentInfo(student2)
    printStudentInfo(student3)

    print("Проверка успеваемости:")
    print(student1.name + ":", checkPerformance(student1.averageGrade))
    print(student2.name + ":", checkPerformance(student2.averageGrade))
    print(student3.name + ":", checkPerformance(student3.averageGrade))

    factNum = int(input("Введите число для вычисления факториала (до 10): "))
    if 0 <= factNum <= 10:
        print(f"Факториал {factNum}! = {factorial(factNum)}")
    else:
        print("Число должно быть от 0 до 10")

    print("Работа с массивом чисел")
    processArray()

    firstName = input("Введите ваше имя: ")
    lastName = input("Введите вашу фамилию: ")
    fullName = firstName + " " + lastName
    print(f"Привет, {fullName}!")
    print(f"Длина вашего полного имени: {len(fullName)} символов")

    print(f"Таблица умножения для {num1}:")
    for i in range(1, 11):
        print(f"{num1} x {i} = {num1 * i}")

if __name__ == '__main__':
    main()